pub mod dvr;
pub mod recording;

use serde::{Deserialize, Serialize};
use std::sync::Arc;
use uuid::Uuid;

use crate::common::VideoCodec;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StreamConfig {
    /// arbitrary identifier for the source generated by the user
    pub source_id: u64,
    pub rtsp_url: url::Url,
    pub username: Option<String>,
    pub password: Option<String>,
    pub should_record: bool,
    pub restart_interval_secs: Option<u64>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum StreamState {
    Stopped,
    Starting,
    Running,
    Error,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StreamInfo {
    pub session_id: u64,
    pub rtsp_url: String,
    pub state: StreamState,
    pub should_record: bool,
    pub webrtc_sessions: Vec<Uuid>,
    pub restart_interval_secs: Option<u64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebRtcSessionConfig {
    pub session_id: Uuid,
    pub source_id: Uuid,
    pub offer: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebRtcSessionInfo {
    pub session_id: Uuid,
    pub source_id: u64,
    pub state: String,
}
